travis:
  secure:
    BINSTAR_TOKEN: crmgQkwORH2/Rf7BGTEeCRf4F3sfukAaZ1O/dLCTPo8/oi43oTafgtFD/b6ju6PBwGTyYVBtDihSg1e/nUH8SBi2R8o5NrUuAloS9hZi872nVuykFfdNqYwUEe4VNQV+HIiCWOm2D6B02U+QsnMdU48NOoXxNd/XqD1NoI/321eyaWdRQO2W/C0YSDlhrOSOJRj1rWzb7DpgaDpnBDVPSnHpIHaVrO5ZdLBEflubHlXyTaHlat8fhTe4vBSNlY3P/TnIyQjftuXVB+QZNNP//pnVTBVPnBs3AQkr6d5i1pTI5BJd13cC/xJ9Ca0mp03+ajZYhgAei6Oh1IngP/1EltjnKSvF1YujknKWlbOa/HRZqYqRy2Rk6uNkOgz9HPvbD4Jblv+kMJ7Z3QfSiPdUeY02Y5VhKjedEueNN+a4QPtWpk7OQm4yjxp3sJh5S9SZ1oihnTi59MYz4/CyLveDUj3Lsll2Gkgda33EtSPbQkdi/zXod7pKI4l0qb5rj9xgKJrGDZf2ysjPs8L2UVkjgk+9Sw7B5bBu42oe9BhTA0ZUSYoUdfzQ/LVEsl5E8dEEAzwwV5udH3maUPg2lVjMRg9aPgGETN/ap2Hw9+tu24j2f1ZTEAfgIaN+V5v8izTok6hSy5dY4tPYqX3Ja2GLV4M2hOYDrWI7gQ83PFfB8Ws=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
